apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: miniflix

resources:
  - ../../base

images:
  - name: miniflix-frontend
    newName: docker.io/YOUR_DOCKERHUB_USERNAME/miniflix-frontend
    newTag: initial
  - name: miniflix-catalog
    newName: docker.io/YOUR_DOCKERHUB_USERNAME/miniflix-catalog
    newTag: initial
